### ISSUE TITLE
[archlinux] Make the image follow all the requirements

### ISSUE THREAD

**Issue by moul** [online-labs/image-archlinux#1]
- [x] Add sysctl entry vm.min_free_kbytes=65536
- [x] Configure NTP to use internal server.
- [x] Configure SSH to only accept login through public keys and deny environment customization to avoid - [ ] errors due to users locale.
- [x] Configure default locale to en_US.UTF-8.
- [x] Configure network scripts to use DHCP and enable them. Although not, strictly speaking, needed since kernel already has IP address and gateway this allows DHCP hooks to be called for setting hostname, etc.
- [x] Install custom DHCP hook for hostname to set entry in /etc/hosts for software using getent_r to get hostname.
- [x] Install scripts to fetch SSH keys
- [x] Install scripts to fetch kernel modules.
- [x] Install scripts to connect and/or mount NBD volumes.
- [x] Install scripts to manage NBD root volume.
- [x] Disable all physical TTY initialization.
- [x] Enable STTY @ 9600 bps.

Original issue: https://github.com/online-labs/image-builder/issues/23

**Comment by s0undt3ch** [comment]
Only one last item to make this image available as an official image?

**Comment by moul** [comment]
@s0undt3ch: not really :)

This image is actually ready, the missing item is not the most blocking one.

---

We want to release this image as a community image and keep our focus on the most used images (ubuntu/debian)/fedora, so today we are just blocked by the web console.

We want to improve the create-server page of the console to highlight the official images and be able to launch more community images, i.e:

- move the current gentoo image to community
- release the archlinux image
- release the openness image
- release the slackware image

**Comment by s0undt3ch** [comment]
I've run Debian in the past, Ubuntu, Fedora, these days I also run some CentOS images on a CI server, but, ever since I moved my Dev system to Arch I've never had more fun managing it(Gentoo was fun too but I needed time to develop :smile:)

I know some Arch'ers which I think would at least be tempted to try the C1 approach.

I've been waiting for this image to move my "always running services" to Online Labs(not much these days, I no longer run my own mail server).

Yesterdays I looked again just to check. I don't want to setup an Ubuntu box just to have to set up another one when Arch comes out.

These days I don't have much free time but when I get some, I'll be creating a Online-Labs driver for salt-cloud(We could use CI testing on a C1) . That might bring some additional attention to your project.

Anyway, looking forward to get my hands on an Arch image :)

Sneek preview? :smile:

**Comment by aimxhaisse** [comment]
Hey @s0undt3ch,

I think the image is nearly ready for a beta, IIRC, there was a booting order issue (I'll check this in a couple of hours), so I think we can have a preview very soon!

**Comment by s0undt3ch** [comment]
Awesome!

**Comment by aimxhaisse** [comment]
LGTM :ok_hand:

**Comment by moul** [comment]
First version released !

---

![coucou](https://www.dropbox.com/s/g5zprmb1c3kyrlr/Screenshot%202015-01-30%2018.27.29.png?dl=1)

---

We experienced a kernel panic during a reboot, probably due to the `nbd` service in the stop sequence order.
If you encounter this behaviour, just click on `Hard reboot` on the web console.
Related issue: #5

---

If you encounter any other issues, you are free to open new issues/PR

**Comment by chmercesmoreira** [comment]
I don't know if here is the correct place to ask for it.
Is it possible to install Arch Linux on the armv8/64 instances?
